Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mess.Models;

namespace mess.Controllers
{
    public class CreateController : Controller
    {
        //
        // GET: /Create/

        public ActionResult Display()
        {
            List<mess.EntFrame.My_Table> a;
            using (var db = new EntFrame.MyDataEntities3())
            {
                a = db.My_Table.ToList();
            }
            return View(a);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(mess.EntFrame.My_Table s, Class1 sa)
        {
            try
            {
                s.ID = sa.ID;
                s.fname = sa.fname;
                s.lname = sa.lname;
                using (var a = new mess.EntFrame.MyDataEntities3())
                {
                    a.My_Table.AddObject(s);
                    a.SaveChanges();
                }
                return RedirectToAction("login");
            }
            catch
            {
                return View();
            }
            
        }

        public ActionResult Edit(int id)
        {
            EntFrame.My_Table t;
            using (var a = new EntFrame.MyDataEntities3())
            {
                t = a.My_Table.Where(v => v.ID == id).FirstOrDefault();
            }
            return View(t);
        }
        [HttpPost]
        public ActionResult Edit(EntFrame.My_Table s)
        {
            EntFrame.My_Table q;
            using (var db = new EntFrame.MyDataEntities3())
            {
                q = db.My_Table.Where(v => v.ID == s.ID).FirstOrDefault();
                q.fname = s.fname;
                q.lname = s.lname;
                

                db.SaveChanges();
            }
            return RedirectToAction("Display");

        }

        public ActionResult Delete(int id)
        {
            EntFrame.My_Table stud;
            using (var a = new EntFrame.MyDataEntities3())
            {
                stud = a.My_Table.Where(v => v.ID == id).FirstOrDefault();
            }
            return View(stud);
        }
        [HttpPost]
        public ActionResult Delete(EntFrame.My_Table s)
        {
            EntFrame.My_Table q;
            using (var db = new EntFrame.MyDataEntities3())
            {
                q = db.My_Table.Where(v => v.ID == s.ID).FirstOrDefault();
                q.fname = s.fname;
                q.lname = s.lname;
                db.My_Table.DeleteObject(q);
                db.SaveChanges();
            }
            return RedirectToAction("Display");

        }
        public ActionResult loaddata()
        {
            using (mess.EntFrame.MyDataEntities3 c = new mess.EntFrame.MyDataEntities3())
            {
                var crazy = c.My_Table.OrderBy(a => a.ID).ToList();
                return Json(new { data = crazy }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult login(EntFrame.My_Table q)
        {

            if (ModelState.IsValid)
            {

                using (mess.EntFrame.MyDataEntities3 a = new mess.EntFrame.MyDataEntities3())
                {


                    var h = a.My_Table.Where(t => t.Uname.Equals(q.Uname) && t.Pword.Equals(q.Pword)).FirstOrDefault();



                    if (h != null)
                    {
                        Session["ID"] = h.ID.ToString();
                        Session["fname"] = h.fname.ToString();
                        return RedirectToAction("Welcome");
                    }


                }
            }
            return View(q);
        }
        public ActionResult Welcome()
        {
            return View();
        }
        public ActionResult Logout()
        {
            return RedirectToAction("Login");
        }
        public ActionResult HomePage()
        {
            return View();
        }
        public ActionResult adminreg()
        {
            return View();
        }
        [HttpPost]
        public ActionResult adminreg(mess.EntFrame.Admin_Data s, Class2 sa)
        {
            try
            {
                s.IDad = sa.IDad;
                s.Fname = sa.Fname;
                s.Lname = sa.Lname;
                
                using (var a = new mess.EntFrame.MyDataEntities4())
                {
                    a.Admin_Data.AddObject(s);
                    a.SaveChanges();
                }
                return RedirectToAction("adminlog");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult adminlog()
        {
            return View();
        }
         [HttpPost]
        public ActionResult adminlog(EntFrame.Admin_Data q)
        {

            if (ModelState.IsValid)
            {

                using (mess.EntFrame.MyDataEntities4 a = new mess.EntFrame.MyDataEntities4())
                {


                    var h = a.Admin_Data.Where(t => t.Uname.Equals(q.Uname) && t.Pword.Equals(q.Pword)).FirstOrDefault();



                    if (h != null)
                    {
                        Session["ID"] = h.IDad.ToString();
                        Session["Fname"] = h.Fname.ToString();
                        return RedirectToAction("AdminPage");
                    }


                }
            }
            return View(q);
        }
        public ActionResult AdminPage()
        {
            return View();
        }
        public ActionResult Admins()
        {
            List<mess.EntFrame.Admin_Data> a;
            using (var db = new EntFrame.MyDataEntities4())
            {
                a = db.Admin_Data.ToList();
            }
            return View(a);
        }
        public ActionResult AddItems()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddItems(mess.EntFrame.Item_Table s)
        {
            try
            {
                using (var a = new mess.EntFrame.MyDataEntities5())
                {
                    a.Item_Table.AddObject(s);
                    a.SaveChanges();
                }
                return RedirectToAction("DisplayItems");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult DisplayItems()
        {
            List<mess.EntFrame.Item_Table> a;
            using (var db = new EntFrame.MyDataEntities5())
            {
                a = db.Item_Table.ToList();
            }
            return View(a);
        }
        public ActionResult EditItem(int id)
        {
            EntFrame.Item_Table t;
            using (var a = new EntFrame.MyDataEntities5())
            {
                t = a.Item_Table.Where(v => v.ItemID == id).FirstOrDefault();
            }
            return View(t);
        }
        [HttpPost]
        public ActionResult EditItem(EntFrame.Item_Table s)
        {
            EntFrame.Item_Table q;
            using (var db = new EntFrame.MyDataEntities5())
            {
                q = db.Item_Table.Where(v => v.ItemID == s.ItemID).FirstOrDefault();
                q.item = s.item;

                db.SaveChanges();
            }
            return RedirectToAction("DisplayItems");

        }
        public ActionResult DeleteItem(int id)
        {
            EntFrame.Item_Table stud;
            using (var a = new EntFrame.MyDataEntities5())
            {
                stud = a.Item_Table.Where(v => v.ItemID == id).FirstOrDefault();
            }
            return View(stud);
        }
        [HttpPost]
        public ActionResult DeleteItem(EntFrame.Item_Table s)
        {
            EntFrame.Item_Table q;
            using (var db = new EntFrame.MyDataEntities5())
            {
                q = db.Item_Table.Where(v => v.ItemID == s.ItemID).FirstOrDefault();
                q.item = s.item;
                q.quant = s.quant;
                db.Item_Table.DeleteObject(q);
                db.SaveChanges();
            }
            return RedirectToAction("DisplayItems");

        }
        /*public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ForgotPassword(EntFrame.My_Table model)
        {
            string emailAddress = WebSecurity.GetEmail(model.UserName);
            if (!string.IsNullOrEmpty(emailAddress))
            {
                string confirmationToken =
                    WebSecurity.GeneratePasswordResetToken(model.UserName);
                dynamic email = new Email("ChngPasswordEmail");
                email.To = emailAddress;
                email.UserName = model.UserName;
                email.ConfirmationToken = confirmationToken;
                email.Send();

                return RedirectToAction("ResetPwStepTwo");
            }

            return RedirectToAction("InvalidUserName");
        }*/

    }
}

Views/Create/AddItems.cshtml
@{
    Layout = null;
}
<html>
<head>
 
<meta name="veiwport" content="width=device-width, initial-scale=1"/>
<link href="~/MyTemp/css/bootstrap.css" rel="stylesheet" type="text/css" />
<script src="~/MyTemp/js/bootstrap.js" type="text/javascript"></script>
<title>eReserve</title>
</head>

<body>
<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
 <div class="navbar-header"><a class="navbar-brand" href="#">BookReservation</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            </div>
             <div class = "collapse navbar-collapse navbar-menubuilder">
        <div class="navbar navbar-custom">
    <ul class="nav navbar-nav">
    <li>@Html.ActionLink("Users", "Display", "Create")</li>
    <li>@Html.ActionLink("Admins", "Admins", "Create")</li>
    </ul>
    <ul class = "nav navbar-nav navbar-right">
     <li>@Html.ActionLink("Logout", "Logout", "Create")</li>
</ul>
        </div>
         </div>
        </div>
 
 @model mess.EntFrame.Item_Table

@using (Html.BeginForm())
{             

    <div class="Container">
        <div class=" registrationform">
   
        <center><h2><span style="color: white">Add Items</span></h2></center>
         <div class="container" style="width:40%; margin-top:2%">
            
            <center><h5>@Html.TextBoxFor(e => e.ItemID, new { @class = "form-control", @placeholder = "Item ID" }) <span style="color:Red"> 
             @Html.ValidationMessageFor(v => v.ItemID, "", new { @class = "error" })</span></h5></center>

            <center><h5>@Html.TextBoxFor(e => e.item, new { @class = "form-control", @placeholder = "Item Name" }) <span style="color:Red">
             @Html.ValidationMessageFor(v => v.item, "", new { @class = "error" })</span></h5></center>

            <center><h5>@Html.TextBoxFor(e => e.quant, new { @class = "form-control", @placeholder = "Quantity" }) <span style="color:Red"> 
            @Html.ValidationMessageFor(v => v.quant, "", new { @class = "error" })</span></h5></center>

             <input type="submit" value="ADD" class="btn btn-block btn-primary" />
        </div>
        </div>
    </div>
}
</body>
</html>  

Views/Create/AdminPage.cshtml
@{
    Layout = null;
}

<html>
<head>
 
<meta name="veiwport" content="width=device-width, initial-scale=1"/>
<link href="~/MyTemp/css/bootstrap.css" rel="stylesheet" type="text/css" />
<script src="~/MyTemp/js/bootstrap.js" type="text/javascript"></script>
<title>eReserve</title>
</head>

<body>
<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
 <div class="navbar-header"><a class="navbar-brand" href="#">BookReservation</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
   <div class = "collapse navbar-collapse navbar-menubuilder">
        <div class="navbar navbar-custom">
    <ul class="nav navbar-nav">
     <li>@Html.ActionLink("Homepage","Index","Home")</li>
      <li>@Html.ActionLink("Users","Display","Create")</li>
      <li>@Html.ActionLink("Admins","Admins","Create")</li>
        <li>@Html.ActionLink("Items","DisplayItems","Create")</li>
         <li>@Html.ActionLink("Add Items","AddItems","Create")</li>
    </ul>
    </ul>
    <ul class = "nav navbar-nav navbar-right">
     <li>@Html.ActionLink("Logout", "Logout", "Create")</li>
</ul>
        </div>
         </div>
    </div>

    @if (Session["fname"] != null)
    {
<text>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Welcome Admin @Session["Fname"].ToString() </h3>
</text>
}
</body>
</html>    


Views/Create/Create.cshtml

@model mess.Models.Class1

@using (Html.BeginForm())
{             

    <div class="Container">
        <div class=" registrationform">
    
        <center><h2><span style="color: white">Book Reserve</span></h2></center>
         <div class="container" style="width:40%; margin-top:2%">
            
            <center><h5>@Html.TextBoxFor(e => e.ID, new { @class = "form-control", @placeholder = "ID Number" }) <span style="color:Red"> 
             @Html.ValidationMessageFor(v => v.ID, "", new { @class = "error" })</span></h5></center>

            <center><h5>@Html.TextBoxFor(e => e.fname, new { @class = "form-control", @placeholder = "First Name" }) <span style="color:Red">
             @Html.ValidationMessageFor(v => v.fname, "", new { @class = "error" })</span></h5></center>

            <center><h5>@Html.TextBoxFor(e => e.lname, new { @class = "form-control", @placeholder = "Last Name" }) <span style="color:Red"> 
            @Html.ValidationMessageFor(v => v.lname, "", new { @class = "error" })</span></h5></center>

             <center><h5>@Html.TextBoxFor(e => e.Uname, new { @class = "form-control", @placeholder = "Username" }) <span style="color:Red">
             @Html.ValidationMessageFor(v => v.Uname, "", new { @class = "error" })</span></h5></center>

            <center><h5>@Html.PasswordFor(e => e.Pword, new { @class = "form-control", @placeholder = "Passsword" }) <span style="color:Red"> 
            @Html.ValidationMessageFor(v => v.Pword, "", new { @class = "error" })</span></h5></center>

             <input type="submit" value="Register" class="btn btn-block btn-primary" />
        </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Create/Delete.cshtml
@model mess.EntFrame.My_Table

@using (Html.BeginForm())
{

<div class = "container">
<div class ="registrationform">
<div class="container" style="width:40%; margin-top:2%">

<center><h5>@Html.TextBoxFor(s => s.ID, new { @class = "form-control", @placeholder = "ID Number" })
@Html.ValidationMessageFor(s => s.ID, "", new { @class = "error" })
</h5></center>

<center><h5> @Html.TextBoxFor(s => s.fname, new { @class = "form-control", @placeholder = "First Name" })
@Html.ValidationMessageFor(s => s.fname, "", new { @class = "error" })
</h5></center>
<center><h5> @Html.TextBoxFor(s => s.lname, new { @class = "form-control", @placeholder = "Last Name" })
@Html.ValidationMessageFor(s => s.lname, "", new { @class = "error" })
</h5></center>


<input type="submit" value="Delete" class="btn btn-block btn-primary"/>
</div>
</div>
</div>

}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Create/DeleteItem.cshtml
@model mess.EntFrame.Item_Table

@using (Html.BeginForm())
{

<div class = "container">
<div class ="registrationform">
 
<div class="container" style="width:40%; margin-top:2%">

<center><h5> @Html.TextBoxFor(s => s.item, new { @class = "form-control", @placeholder = "First Name" })
@Html.ValidationMessageFor(s => s.item, "", new { @class = "error" })
</h5></center>
<center><h5> @Html.TextBoxFor(s => s.quant, new { @class = "form-control", @placeholder = "Last Name" })
@Html.ValidationMessageFor(s => s.quant, "", new { @class = "error" })
</h5></center>

<input type="submit" value="Delete" class="btn btn-block btn-primary"/>
</div>
</div>
</div>

}

Views/Create/DisplayItems.cshtml
@{
    Layout = null;
}
<html>
<head>
<meta name="veiwport" content="width=device-width, initial-scale=1"/>
<link href="~/MyTemp/css/bootstrap.css" rel="stylesheet" type="text/css" />
<script src="~/MyTemp/js/bootstrap.js" type="text/javascript"></script>
<title>eReserve</title>
</head>

<body>
<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
 <div class="navbar-header"><a class="navbar-brand" href="#">Book Reserve</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            </div>
             <div class = "collapse navbar-collapse navbar-menubuilder">
        <div class="navbar navbar-custom">
    <ul class="nav navbar-nav">
    <li>@Html.ActionLink("Users", "Display", "Create")</li>
    <li>@Html.ActionLink("Admins", "Admins", "Create")</li>
    </ul>
    <ul class = "nav navbar-nav navbar-right">
     <li>@Html.ActionLink("Logout", "Logout", "Create")</li>
</ul>
        </div>
         </div>
        </div>
    </div>
@model List<mess.EntFrame.Item_Table>
<link href="~/MyTemp/css/style.css" rel="stylesheet" type="text/css" />
<div style="width:90%; margin:0 auto;">
<table>
<thead>
<tr>
<th>Item ID</th>
<th>Item Name</th>
<th>Quantity</th>
<th>Reserve Now!</th>
<td>
@foreach (var a in Model)
 { 
      <tr>
      <td><center> @a.ItemID</center></td>
      <td><center> @a.item</center></td>
      <td><center>@a.quant</center></td>
      <td>
        <a href ="/Create/EditItem/@a.ItemID">Edit</a>
        <a href ="/Create/DeleteItem/@a.ItemID">Delete</a>
     </td>
     </tr>
 }
 </td>
 </tr>
</thead>
</table>
</div>
</body>
</html>  

 

Views/Create/Edit.cshtml
@model mess.EntFrame.My_Table

@using (Html.BeginForm())
{

<div class = "container">
<div class ="registrationform">
<div class="container" style="width:40%; margin-top:2%">

<center><h5>@Html.TextBoxFor(s => s.ID, new { @class = "form-control", @placeholder = "ID Number" })
@Html.ValidationMessageFor(s => s.ID, "", new { @class = "error" })
</h5></center>

<center><h5> @Html.TextBoxFor(s => s.fname, new { @class = "form-control", @placeholder = "First Name" })
@Html.ValidationMessageFor(s => s.fname, "", new { @class = "error" })
</h5></center>
<center><h5> @Html.TextBoxFor(s => s.lname, new { @class = "form-control", @placeholder = "Last Name" })
@Html.ValidationMessageFor(s => s.lname, "", new { @class = "error" })
</h5></center>

<input type="submit" value="Edit" class="btn btn-block btn-primary"/>
</div>
</div>
</div>

}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Create/EditItem.cshtml
@model mess.EntFrame.Item_Table

@using (Html.BeginForm())
{

<div class = "container">
<div class ="registrationform"> 
<div class="container" style="width:40%; margin-top:2%">

<center><h5> @Html.TextBoxFor(s => s.item, new { @class = "form-control", @placeholder = "First Name" })
@Html.ValidationMessageFor(s => s.item, "", new { @class = "error" })
</h5></center>
<center><h5> @Html.TextBoxFor(s => s.quant, new { @class = "form-control", @placeholder = "Last Name" })
@Html.ValidationMessageFor(s => s.quant, "", new { @class = "error" })
</h5></center>

<input type="submit" value="Edit" class="btn btn-block btn-primary"/>
</div>
</div>
</div>

}

Views/Create/HomePage.cshtml
@{
    Layout = null;
}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/MyTemp/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>

<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">1 / 3</div>
  <img src="img_nature_wide.jpg" style="width:100%">
  <div class="text">Caption Text</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 3</div>
  <img src="img_fjords_wide.jpg" style="width:100%">
  <div class="text">Caption Two</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 3</div>
  <img src="img_mountains_wide.jpg" style="width:100%">
  <div class="text">Caption Three</div>
</div>

<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
<a class="next" onclick="plusSlides(1)">&#10095;</a>

</div>
<br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
</div>

<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        if (n > slides.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = slides.length }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";
    }
</script>

</body>
</html> 

Views/Create/Logout.cshtml
@{
    ViewBag.Title = "Logout";
}

<h2>Logout</h2>

Views/Create/Welcome.cshtml
@{
    Layout = null;
}

<html>
<head>
<meta name="veiwport" content="width=device-width, initial-scale=1"/>
<link href="~/MyTemp/css/bootstrap.css" rel="stylesheet" type="text/css" />
<script src="~/MyTemp/js/bootstrap.js" type="text/javascript"></script>

</head>

<body>
<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
 <div class="navbar-header"><a class="navbar-brand" href="#">Book Reserve</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
   <div class = "collapse navbar-collapse navbar-menubuilder">
        <div class="navbar navbar-custom">
    <ul class="nav navbar-nav">
     <li>@Html.ActionLink("Homepage","Index","Home")</li>
    <li>@Html.ActionLink("About Us", "About", "Home")</li>
    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
    </ul>
    <ul class = "nav navbar-nav navbar-right">
     <li>@Html.ActionLink("Logout", "Logout", "Create")</li>
</ul>
        </div>
         </div>
    </div>
    
    <div class="Container">
        <div class=" registrationform">
    @if (Session["fname"] != null)
    {
<text>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Welcome to Book Reserve @Session["fname"].ToString() </h3>
</text>
}
<form method="get" enctype="application/x-www-form-urlencoded" action="/html/codes/html_form_handler.cfm">

<p>
<label>Full Name
<input class="crazy" type="text" name="customer_name" required>
</label> 
</p>

<p>
<label>Phone 
<input class="crazy" type="tel" name="phone_number">
</label>
</p>


<fieldset>
<legend>Books Menu</legend>
<p><label> <input class="crazy" type="radio" name="taxi" required value="bok"> HISTORY </label></p>
<p><label> <input class="crazy" type="radio" name="taxi" required value="ash"> BIOLOGY </label></p>
<p><label> <input class="crazy" type="radio" name="taxi" required value="ssh"> MATH </label></p>
<p><label> <input class="crazy" type="radio" name="taxi" required value="ssh"> ENGLISH </label></p>
<p><label> <input class="crazy" type="radio" name="taxi" required value="ssh"> SCIENCE</label></p>
</fieldset>






</div>
<p class="crazy"><button>Submit Reservation</button></p>

</form>
   </div>
        </div>
</body>
</html>    

Views/Create/adminlog.cshtml
@{
    Layout = null;
}
<html>
<head>

<meta name="veiwport" content="width=device-width, initial-scale=1"/>
<link href="~/MyTemp/css/bootstrap.css" rel="stylesheet" type="text/css" />
<script src="~/MyTemp/js/bootstrap.js" type="text/javascript"></script>
<title>eReserve</title>
</head>

<body>
<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
 <div class="navbar-header"><a class="navbar-brand" href="#">BookReservation</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
   <div class = "collapse navbar-collapse navbar-menubuilder">
        <div class="navbar navbar-custom">
    <ul class="nav navbar-nav">
     <li>@Html.ActionLink("Homepage","Index","Home")</li>
    <li>@Html.ActionLink("About Us", "About", "Home")</li>
    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
    </ul>
        </div>
         </div>
    </div>
   @model mess.Models.Class2

@using (Html.BeginForm())
{             

    <div class="Container">
        <div class="registrationform">
        
        <center><h2><span style="color: White">Welcome Admin</span></h2></center>
         <div class="container" style="width:40%; margin-top:2%">
            
           <center><h5>@Html.TextBoxFor(e => e.Uname, new { @class = "form-control", @placeholder = "Username" }) <span style="color:Red">
             @Html.ValidationMessageFor(v => v.Uname, "", new { @class = "error" })</span></h5></center>
            <center><h5>@Html.PasswordFor(e => e.Pword, new { @class = "form-control", @placeholder = "Passsword" }) <span style="color:Red"> 
            @Html.ValidationMessageFor(v => v.Pword, "", new { @class = "error" })</span></h5></center>
            <input type="submit" value="Login" class="btn btn-block btn-primary" />
        </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Views/Create/adminreg.cshtml

@model mess.Models.Class2

@using (Html.BeginForm())
{             

    <div class="Container">
        <div class=" registrationform">
        <center><h2><span style="color: white">eReserve Registration</span></h2></center>
         <div class="container" style="width:40%; margin-top:2%">
            
            <center><h5>@Html.TextBoxFor(e => e.IDad, new { @class = "form-control", @placeholder = "ID Number" }) <span style="color:Red"> 
             @Html.ValidationMessageFor(v => v.IDad, "", new { @class = "error" })</span></h5></center>

            <center><h5>@Html.TextBoxFor(e => e.Fname, new { @class = "form-control", @placeholder = "First Name" }) <span style="color:Red">
             @Html.ValidationMessageFor(v => v.Fname, "", new { @class = "error" })</span></h5></center>

            <center><h5>@Html.TextBoxFor(e => e.Lname, new { @class = "form-control", @placeholder = "Last Name" }) <span style="color:Red"> 
            @Html.ValidationMessageFor(v => v.Lname, "", new { @class = "error" })</span></h5></center>


             <center><h5>@Html.TextBoxFor(e => e.Uname, new { @class = "form-control", @placeholder = "Username" }) <span style="color:Red">
             @Html.ValidationMessageFor(v => v.Uname, "", new { @class = "error" })</span></h5></center>

            <center><h5>@Html.PasswordFor(e => e.Pword, new { @class = "form-control", @placeholder = "Passsword" }) <span style="color:Red"> 
            @Html.ValidationMessageFor(v => v.Pword, "", new { @class = "error" })</span></h5></center>

             <input type="submit" value="Register" class="btn btn-block btn-primary" />
        </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Create/loaddata.cshtml
@*@{
    ViewBag.Title = "loaddata";
}

<h2>loaddata</h2>